"""
Demo Data — dashboard/demo_data.py

Pre-seeded, realistic incident data for Streamlit Community Cloud demo mode.
All values are derived from actual benchmark runs (see README.md §Benchmark Numbers).

Used by all dashboard pages when api_url is None (Demo Mode).
"""

from __future__ import annotations

DEMO_INCIDENTS: list[dict] = [
    # Scenario A — Moderate Line Fault (Guardrail: PASS)
    {
        "incident_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "fault_type": "line_fault",
        "severity": "CRITICAL",
        "confidence": 1.000,
        "guardrail_status": "PASS",
        "resolved": True,
        "total_latency_ms": 412,
        "created_at": "2026-04-16T08:14:32",
        "voltage_pu": 0.78,
        "current_pu": 1.4,
        "frequency_hz": 49.5,
        "action_steps": [
            "Monitor voltage levels continuously for next 15 minutes",
            "Issue alert to grid operations team via SCADA",
            "Verify protective relay settings at affected bus",
            "Log event in IEC 61968 compliant incident register",
        ],
        "references": ["IEC 61850 §6.2.1", "IEEE C37.2-2008 §4.3"],
        "agent_trace": {
            "supervisor": {"status": "ok", "latency_ms": 5},
            "fault_analyzer": {"status": "ok", "latency_ms": 52, "wavelet_bands": 4},
            "remediation_agent": {"status": "ok", "latency_ms": 318, "rag_docs": 5},
            "guardrail_engine": {"status": "PASS", "latency_ms": 2, "llm_calls": 0},
            "report_generator": {"status": "ok", "latency_ms": 35},
        },
    },
    # Scenario B — Severe Line Fault (Guardrail: BLOCK)
    {
        "incident_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        "fault_type": "line_fault",
        "severity": "CRITICAL",
        "confidence": 1.000,
        "guardrail_status": "BLOCK",
        "resolved": False,
        "total_latency_ms": 398,
        "created_at": "2026-04-16T08:22:11",
        "voltage_pu": 0.30,
        "current_pu": 2.5,
        "frequency_hz": 48.8,
        "action_steps": [
            "Isolate affected transmission segment via remote switching",
            "Open circuit breaker CB-14A at substation Bravo",
            "De-energize line section for crew safety prior to inspection",
            "Initiate load transfer to adjacent feeder circuits",
        ],
        "references": ["IEC 61850 §8.1.3", "IEC 61968 §5.4.2"],
        "agent_trace": {
            "supervisor": {"status": "ok", "latency_ms": 4},
            "fault_analyzer": {"status": "ok", "latency_ms": 48, "wavelet_bands": 4},
            "remediation_agent": {"status": "ok", "latency_ms": 310, "rag_docs": 5},
            "guardrail_engine": {"status": "BLOCK", "latency_ms": 3, "llm_calls": 0,
                                 "triggered_keywords": ["isolate", "circuit breaker", "de-energize"]},
            "report_generator": {"status": "ok", "latency_ms": 33},
        },
    },
    # Scenario C — Normal Operation
    {
        "incident_id": "c3d4e5f6-a7b8-9012-cdef-123456789012",
        "fault_type": "normal",
        "severity": "LOW",
        "confidence": 1.000,
        "guardrail_status": "PASS",
        "resolved": True,
        "total_latency_ms": 8,
        "created_at": "2026-04-16T08:30:05",
        "voltage_pu": 1.01,
        "current_pu": 0.45,
        "frequency_hz": 50.0,
        "action_steps": [],
        "references": [],
        "agent_trace": {
            "supervisor": {"status": "ok", "latency_ms": 3},
            "fault_analyzer": {"status": "ok", "latency_ms": 4, "wavelet_bands": 4},
            "report_generator": {"status": "ok", "latency_ms": 1},
        },
    },
    # Extra: Voltage Sag (MEDIUM)
    {
        "incident_id": "d4e5f6a7-b8c9-0123-defa-234567890123",
        "fault_type": "voltage_sag",
        "severity": "MEDIUM",
        "confidence": 0.712,
        "guardrail_status": "PASS",
        "resolved": True,
        "total_latency_ms": 385,
        "created_at": "2026-04-16T09:05:44",
        "voltage_pu": 0.88,
        "current_pu": 0.9,
        "frequency_hz": 49.8,
        "action_steps": [
            "Activate tap changer control on transformer T-03",
            "Enable capacitor bank CB-07A for reactive compensation",
            "Log voltage profile deviation in SCADA historian",
        ],
        "references": ["IEC 61968 Voltage Sag §3.2", "IEEE 1159-2019 §5.1"],
        "agent_trace": {
            "supervisor": {"status": "ok", "latency_ms": 4},
            "fault_analyzer": {"status": "ok", "latency_ms": 50},
            "remediation_agent": {"status": "ok", "latency_ms": 298, "rag_docs": 5},
            "guardrail_engine": {"status": "PASS", "latency_ms": 2, "llm_calls": 0},
            "report_generator": {"status": "ok", "latency_ms": 31},
        },
    },
    # Extra: Overcurrent (HIGH)
    {
        "incident_id": "e5f6a7b8-c9d0-1234-efab-345678901234",
        "fault_type": "overcurrent",
        "severity": "HIGH",
        "confidence": 0.960,
        "guardrail_status": "PASS",
        "resolved": True,
        "total_latency_ms": 423,
        "created_at": "2026-04-16T10:18:22",
        "voltage_pu": 0.95,
        "current_pu": 1.85,
        "frequency_hz": 49.9,
        "action_steps": [
            "Reduce load on Phase C via automated demand response",
            "Check thermal limits on conductor C-19 segment",
            "Coordinate with distribution operators for load shedding",
            "Verify overcurrent relay pickup settings IEC 60909",
        ],
        "references": ["IEC 60909 §6.3", "IEEE C37.112-2018 §3.5"],
        "agent_trace": {
            "supervisor": {"status": "ok", "latency_ms": 5},
            "fault_analyzer": {"status": "ok", "latency_ms": 55},
            "remediation_agent": {"status": "ok", "latency_ms": 328, "rag_docs": 5},
            "guardrail_engine": {"status": "PASS", "latency_ms": 2, "llm_calls": 0},
            "report_generator": {"status": "ok", "latency_ms": 33},
        },
    },
]

DEMO_METRICS: dict = {
    "total_incidents": 5,
    "resolution_rate": 80.0,   # 4/5 resolved (1 BLOCK pending)
    "guardrail_block_count": 1,
    "avg_latency_ms": 325.2,
    "fault_type_distribution": {
        "line_fault": 2,
        "normal": 1,
        "voltage_sag": 1,
        "overcurrent": 1,
    },
    "guardrail_distribution": {
        "PASS": 4,
        "WARN": 0,
        "BLOCK": 1,
    },
    "severity_distribution": {
        "LOW": 1,
        "MEDIUM": 1,
        "HIGH": 1,
        "CRITICAL": 2,
    },
}

# Pre-computed A/B benchmark results matching README §A/B Comparison table
DEMO_AB_RESULTS: list[dict] = [
    {
        "scenario":         "Normal Operation",
        "expected_fault":   "normal",
        "v1_fault_type":    "normal",
        "v2_fault_type":    "normal",
        "v1_confidence":    0.956,
        "v2_confidence":    1.000,
        "confidence_delta": +0.044,
        "v1_latency_ms":    9,
        "v2_latency_ms":    8,
        "v1_guardrail":     "PASS",
        "v2_guardrail":     "PASS",
        "v1_correct":       True,
        "v2_correct":       True,
    },
    {
        "scenario":         "Voltage Sag",
        "expected_fault":   "voltage_sag",
        "v1_fault_type":    "voltage_sag",
        "v2_fault_type":    "voltage_sag",
        "v1_confidence":    0.678,
        "v2_confidence":    0.712,
        "confidence_delta": +0.034,
        "v1_latency_ms":    336,
        "v2_latency_ms":    385,
        "v1_guardrail":     "PASS",
        "v2_guardrail":     "PASS",
        "v1_correct":       True,
        "v2_correct":       True,
    },
    {
        "scenario":         "Overcurrent",
        "expected_fault":   "overcurrent",
        "v1_fault_type":    "overcurrent",
        "v2_fault_type":    "overcurrent",
        "v1_confidence":    0.922,
        "v2_confidence":    0.960,
        "confidence_delta": +0.038,
        "v1_latency_ms":    371,
        "v2_latency_ms":    423,
        "v1_guardrail":     "PASS",
        "v2_guardrail":     "PASS",
        "v1_correct":       True,
        "v2_correct":       True,
    },
    {
        "scenario":         "Line Fault (Moderate)",
        "expected_fault":   "line_fault",
        "v1_fault_type":    "line_fault",
        "v2_fault_type":    "line_fault",
        "v1_confidence":    0.956,
        "v2_confidence":    1.000,
        "confidence_delta": +0.044,
        "v1_latency_ms":    361,
        "v2_latency_ms":    412,
        "v1_guardrail":     "PASS",
        "v2_guardrail":     "PASS",
        "v1_correct":       True,
        "v2_correct":       True,
    },
    {
        "scenario":         "Line Fault (Severe)",
        "expected_fault":   "line_fault",
        "v1_fault_type":    "line_fault",
        "v2_fault_type":    "line_fault",
        "v1_confidence":    0.956,
        "v2_confidence":    1.000,
        "confidence_delta": +0.044,
        "v1_latency_ms":    348,
        "v2_latency_ms":    398,
        "v1_guardrail":     "BLOCK",
        "v2_guardrail":     "BLOCK",
        "v1_correct":       True,
        "v2_correct":       True,
    },
]
